language: java
script: mvn -f openpythia/pom.xml clean verify
notifications:
  email: false
deploy:
  provider: bintray
  user: dennisrippinger
  key: '$BINTRAY_API_KEY'
  file: ./bintray.json
  skip_cleanup: true
